version: '3.1'

volumes:
  pg_data:

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=quartz_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
